project:
  type: website

website:
  navbar:
    center: 
      - "Blogs by Aryan"
  search: false  

format:
  html:
    includes:
      in-header: 
        - styles.css
        - about_styles.css
      

publish:
  gh-pages:
    branch: gh-pages
    url: https://ads0094.github.io/Blogs/


