project:
  type: website

website:
  title: "Blogs by Aryan"
  navbar:
    right:
      - text: ""
        href: index.html
      - text: "Blog-Posts"
        href: posts.html
      - icon: github
        href: https://github.com/ads0094/Blogs

format:
  html:
    includes:
      in-header: 
        - styles.css
        - about_styles.css
      

publish:
  gh-pages:
    branch: gh-pages
    url: https://ads0094.github.io/Blogs/


