project:
  type: website

website:
  title: "Economics"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/ads0094/Blogs

publish:
  gh-pages:
    branch: gh-pages
    url: https://ads0094.github.io/Blogs/

